apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-k8s-admin
  namespace: awx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-k8s-admin
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - services
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awx-k8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awx-k8s-admin
subjects:
  - kind: ServiceAccount
    name: awx-k8s-admin
    namespace: awx

